# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class Acquiesce:
    @classmethod
    def from_repo(cls, hf_cache_path:builtins.str, model_id:builtins.str, revision:typing.Optional[builtins.str]) -> Acquiesce: ...
    def render(self, messages_json:builtins.str, tools_json:builtins.str, tool_choice_json:builtins.str, parallel_tool_calls:builtins.bool) -> RenderResult: ...

@typing.final
class Parser:
    def parse(self, _text:builtins.str) -> builtins.list[builtins.str]: ...

@typing.final
class RenderResult:
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def grammar(self) -> typing.Optional[builtins.str]: ...
    @property
    def parser(self) -> typing.Optional[Parser]: ...

