/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AcquiesceHandle {
  constructor(path: string, fallbackName?: string | undefined | null)
  transformAsync(): Promise<Array<number>>
}

export declare function heavyTransform(input: Buffer): Promise<Array<number>>
